language: python
# Versions on https://docs.travis-ci.com/user/languages/python/
python:
    - "3.6"
    - "3.7"
    - "3.7-dev"
    # - "3.8-dev"

# Command to install dependencies.
install:
    - pip install pipenv
    - make install-dev

# Command to run tests.
script: make lint
